Repository opendistro-for-elasticsearch/alerting-kibana-plugin, pull requests merged in 2020-10, with the labels that each got.

#182 Show error message for the failed monitor runs in dashboard
  public/pages/Dashboard/utils/tableUtils.js
Labels: enhancement

#187 Show name of the user who last updated the monitor in Monitor Dashboard and Detail page
  public/pages/MonitorDetails/components/MonitorOverview/__snapshots__/MonitorOverview.test.js.snap
  public/pages/MonitorDetails/components/MonitorOverview/utils/getOverviewStats.js
  public/pages/MonitorDetails/components/MonitorOverview/utils/getOverviewStats.test.js
  public/pages/Monitors/containers/Monitors/__snapshots__/Monitors.test.js.snap
  public/pages/Monitors/containers/Monitors/utils/tableUtils.js
Labels: feature

#168 Add a toast message and auto scroll to the 1st error field when failed to create/update a monitor or destination
  public/pages/CreateMonitor/containers/ConfigureMonitor/ConfigureMonitor.js
  public/pages/CreateMonitor/containers/CreateMonitor/CreateMonitor.js
  public/pages/CreateTrigger/components/Action/utils/constants.js
  public/pages/Destinations/components/DestinationsList/DestinationsActions/DestinationsActions.js
  public/pages/Destinations/components/createDestinations/CustomWebhook/URLInfo.js
  public/pages/Destinations/components/createDestinations/Webhook/Webhook.js
  public/pages/Destinations/containers/CreateDestination/CreateDestination.js
  public/pages/Destinations/containers/CreateDestination/EmailSender/utils/validate.js
  public/pages/Destinations/containers/CreateDestination/ManageEmailGroups/utils/helpers.js
  public/utils/SubmitErrorHandler.js
  public/utils/helpers.js
Labels: enhancement

#204 Pass in isEmailAllowed for Email modals on CreateDestination page
  public/pages/Destinations/containers/CreateDestination/EmailRecipients/EmailRecipients.js
  public/pages/Destinations/containers/CreateDestination/EmailSender/EmailSender.js
Labels: bug
