Repository opendistro-for-elasticsearch/alerting-kibana-plugin, pull requests merged in 2020-12, with the labels that each got.

#217 Updates the release notes for 1.12.0.0
  release-notes/opendistro-for-elasticsearch-alerting-kibana-plugin.release-notes-1.12.0.0.md
Labels: documentation

#90 Allow for http method selection in custom webhook
  public/pages/Destinations/components/createDestinations/CustomWebhook/CustomWebhook.js
  public/pages/Destinations/components/createDestinations/CustomWebhook/HeaderParamsEditor.js
  public/pages/Destinations/components/createDestinations/CustomWebhook/MethodEditor.js
  public/pages/Destinations/containers/CreateDestination/utils/__tests__/destinationToFormik.test.js
  public/pages/Destinations/containers/CreateDestination/utils/__tests__/formikToDestination.test.js
  public/pages/Destinations/containers/CreateDestination/utils/constants.js
Labels: next-release

#223 Remove 'JSON.stringify()' from constructing the body of API calls in request handlers
  server/services/DestinationsService.js
  server/services/MonitorService.js
Labels: refactor

#230 Fix that Trigger page might freeze for high cardinality detectors
  public/pages/CreateMonitor/components/AnomalyDetectors/AnomaliesChart/AnomaliesChart.js
  public/pages/CreateMonitor/components/AnomalyDetectors/AnomaliesChart/AnomaliesChart.test.js
  public/pages/CreateTrigger/containers/CreateTrigger/utils/constants.js
  public/pages/CreateTrigger/containers/CreateTrigger/utils/formikToTrigger.test.js
  public/pages/CreateTrigger/containers/DefineTrigger/AnomalyDetectorTrigger.js
Labels: bug

#229 Filter out historical detectors on monitor creation page
  public/pages/CreateMonitor/containers/AnomalyDetectors/AnomalyDetectors.js
Labels: bug
